# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 笑忘歌
email: silence@liujianxing.com
description: > # this means to ignore newlines until "baseurl:"
  Hope is a waking dream.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.liujianxing.com" # the base hostname & protocol for your site

github_username:  EEternal

# Build settings
markdown: kramdown
